title: 筆記
description: 數學、計算機科學與其他舊筆記。
url: "https://davidhu3141.github.io"
baseurl: ""
lang: zh-Hant-TW
timezone: Asia/Taipei

github_username: davidhu3141

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: /:categories/:year/:month/:day/:title.html

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - pLaTex.sh
  - _deprecated
  - _editing_md
  - _NormalFiles
  - work
